### ISSUE TITLE
CNCF Incubation

### ISSUE THREAD

**Issue by beeme1mr** [open-feature/.github#19]
## Overview

The CNCF associates a maturity level with every project. OpenFeature is currently a sandbox project, which is the entry point for early stage projects. Incubation status provides a number of benefits to the project including access to additional CNCF services and production readiness guarantees. That's why incubation status is important to the long-term success of the project.

## Requirements

> Note: The incubation level is the point at which we expect to perform full [due diligence](https://github.com/cncf/toc/blob/main/process/due-diligence-guidelines.md) on projects.

To be accepted to incubating stage, a project must meet the sandbox stage requirements plus:

- [x] Document that it is being used successfully in production by at least three independent direct adopters which, in the TOC’s judgement, are of adequate quality and scope. For the definition of an adopter, see https://github.com/cncf/toc/blob/main/FAQ.md#what-is-the-definition-of-an-adopter.
- [x] Have a healthy number of committers. A committer is defined as someone with the commit bit; i.e., someone who can accept contributions to some or all of the project.
- [x] Demonstrate a substantial ongoing flow of commits and merged contributions.
- [x] Since these metrics can vary significantly depending on the type, scope and size of a project, the TOC has final judgement over the level of activity that is adequate to meet these criteria
- [x] A clear versioning scheme.
- [x] Clearly documented security processes explaining how to report security issues to the project, and describing how the project provides updated releases or patches to resolve security vulnerabilities
- [x] Specifications must have at least one public reference implementation.

## References

- [Incubation PR](https://github.com/cncf/toc/pull/985)
- [Graduation criteria](https://github.com/cncf/toc/blob/main/process/graduation_criteria.md)
- [Incubation Proposal Fork](https://github.com/open-feature/toc-proposal/blob/main/proposals/incubation/openfeature.md)

**Comment by oldukhno** [comment]
I'm curious how far we are from getting to the CNCF incubation at this point?

**Comment by beeme1mr** [comment]
@oldukhno we're 1 binding vote away! There was a freeze for KubeCon. Hopefully, we'll get the last vote soon.

https://github.com/cncf/toc/pull/985#issuecomment-1811432038

**Comment by oldukhno** [comment]
Thanks for responding. We are evaluating the possibility of using and contributing to OpenFeature, and the growing maturity of CNCF is one of the cornerstones in making this decision.

**Comment by beeme1mr** [comment]
The CNCF has promoted OpenFeature from sandbox to incubation. A press release will be sent later this week.

**Comment by beeme1mr** [comment]
https://www.cncf.io/blog/2023/12/19/openfeature-becomes-a-cncf-incubating-project/
