### ISSUE TITLE
[go-sdk] Review repository compliance

### ISSUE THREAD

**Issue by toddbaert** [open-feature/.github#23]
Review repository compliance with respect to the [requirements](https://github.com/open-feature/.github/blob/main/CONTRIBUTING.md#repository-requirements). Investigate which recommendations can be implemented and how, and create issues for each with the "security" label.

Resulting issues: https://github.com/open-feature/go-sdk/search?q=label%3Asecurity&type=issues

**Comment by toddbaert** [comment]
@skyerus I think you've done this based on [this query](https://github.com/open-feature/go-sdk/search?q=label%3Asecurity&type=issues). I'm closing. Please re-open if I'm wrong.

**Comment by skyerus** [comment]
@toddbaert issues are open to resolve all of the missing requirements.
