### ISSUE TITLE
[go-sdk-contrib] Review repository compliance

### ISSUE THREAD

**Issue by toddbaert** [open-feature/.github#24]
Review repository compliance with respect to the [requirements](https://github.com/open-feature/.github/blob/main/CONTRIBUTING.md#repository-requirements). Investigate which recommendations can be implemented and how, and create issues for each with the "security" label.

Resulting issues: https://github.com/open-feature/go-sdk-contrib/search?q=label%3Asecurity&type=issues

**Comment by james-milligan** [comment]
## automated publishing
issue opened to configure release please to handle the release process for both `providers` and `hooks`, using the `js-sdk-contribs` as a template: https://github.com/open-feature/go-sdk-contrib/issues/73

## container / base image scanning
No containers are created within this repository

## code ownership
There is currently branch protection on `main`, a PR is required to push to `main` requiring 2 approvals.
`CODEOWNERS` could be set up for individual `providers` or `hooks`, however, I believe this should be a decision made by the developer initially creating the `provider`/`hook` and can be handled internally to the package 

## dependency analysis
Dependency analysis is currently being managed by Snyk (watching the org) 

## dependency autoupdates
Opened an issue to configure renovate 
https://github.com/open-feature/go-sdk-contrib/issues/74

## fuzzing
As this is a `go` project, fuzzing is available out of the box and can be used to expand existing unit tests, I don't believe that a third party tool will be necessary here.
> is it worth adding a `CONTRIBUTING.md` with a recommendation to include `go fuzzing` in unit tests? 
https://go.dev/security/fuzz/

## SBOM generation
Opened an issue to configure `cycloneDX/cyclonedx-gomod`
https://github.com/open-feature/go-sdk-contrib/issues/75

## static analysis
The project currently uses `github.com/golangci/golangci-lint/cmd/golangci-lint@latest` to lint the project on PR updates.

## unit, integration testing
Unit tests and integration tests should be handled by individual modules, although this links back to 'fuzzing' where its may be worthwhile adding a list of 'standards' in a `CONTRIBUTING.md` file
